# This is the template of the k8s job launched whenever a subproject is created or updated.
# Template variables that will be replaced by the launcher (the Dataset-service):
#   __PROJECT_CODE__, __SUBPROJECT_CODE__, __SUBPROJECT_NAME__, __SUBPROJECT_DESCRIPTION__, __SUBPROJECT_EXTERNAL_ID__
# NOTE: the script for create (create-project.sh) should be idempotent, the result should be the same if called multiple times.

apiVersion: batch/v1
kind: Job
metadata:
  # name: it is set by the caller
  # namespace: it is set by the caller
spec:
  template:
    spec:
      volumes:
        - name: dataset-service-data-volume
          persistentVolumeClaim:
            claimName: dataset-service-data

      containers:
        - name: subproject-management
          image: harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-services/dataset-service-on-event-jobs:1.0
          imagePullPolicy: Always
          workingDir: "/home/ubuntu/scripts"
          command: ["/bin/bash"]
          args: ["/home/ubuntu/scripts/create-subproject.sh"]
          volumeMounts:
            - mountPath: "/home/ubuntu/scripts"
              subPath: "on-event-jobs/scripts"
              name: dataset-service-data-volume
          env:
            - name: PROJECT_CODE
              value: "__PROJECT_CODE__"
            - name: SUBPROJECT_CODE
              value: "__SUBPROJECT_CODE__"
            - name: SUBPROJECT_NAME
              value: "__SUBPROJECT_NAME__"
            - name: SUBPROJECT_DESCRIPTION
              value: "__SUBPROJECT_DESCRIPTION__"
            - name: SUBPROJECT_EXTERNAL_ID
              value: "__SUBPROJECT_EXTERNAL_ID__"
              
      restartPolicy: Never  # no restart container if fails
  backoffLimit: 0   # no retry to launch pod if fails
  ttlSecondsAfterFinished: 86400   # auto remove the job 24 hours after finish
