apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataset-service-backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dataset-service-backend
rules:
  # below are required to manage jobs for dataset creation and user management scripts
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list"]
  # get deployments is required to copy some parts of the main service deployment to the jobs
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  # two below apiGroups are required to get the output logs of the jobs launched
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/status"]
    verbs: ["get"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dataset-service-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dataset-service-backend
subjects:
  - kind: ServiceAccount
    name: dataset-service-backend
    namespace: dataset-service
